### ISSUE TITLE
Readability.article(raw_html) encounter error

### ISSUE THREAD

**Issue by rupertqin** [keepcosmos/readability#23]
v: 0.6.1

```
** (FunctionClauseError) no function clause matching in Floki.DeepText.get_text/3
    lib/floki/deep_text.ex:28: Floki.DeepText.get_text(nil, "", "")
    lib/readability/helper.ex:75: Readability.Helper.text_length/1
    lib/readability/article_builder.ex:38: Readability.ArticleBuilder.build/2
```

**Comment by keepcosmos** [comment]
Can you give me your example site url or html document?

**Comment by rupertqin** [comment]
@keepcosmos  for example https://www.douban.com/note/603462275/

**Comment by JosephHalter** [comment]
Also crashes with the same error on many english pages, for example any article I tried from The New York Times https://www.nytimes.com/2017/01/30/us/immigration-ban-locations.html?_r=0

**Comment by keepcosmos** [comment]
@rupertqin Thanks for reporting. It fixed. try v 0.7.0

@JosephHalter Your error also fixed. But it was different case. Your url return 303. Maybe it is httpoison issue. Plz check [here](https://github.com/keepcosmos/readability/blob/master/lib/readability.ex#L75)

**Comment by rupertqin** [comment]
@keepcosmos  still not work, it alarms ** (UndefinedFunctionError) function Floki.Selector.match?/2 is undefined or private. Did you mean one of:

      * match?/3

**Comment by rupertqin** [comment]
## In most case, `Readability.summarize` is always work, but in my case, I need `Readability.article`, it's my code: 

```elixir
case HTTPoison.get("http://zh.html.net/tutorials/css/lesson3.php", @headers, @request_options) do
      {:ok, response} ->
        case response.status_code do
          200 ->
            response.body
            |> IO.inspect
            |> Readability.article
            |> IO.inspect
          _ ->
            "no match"
        end
      {:error, _response} ->
        IO.inspect "BAD LINK 4xx"
      _ ->
        IO.inspect "BAD LINK 5xx"
    end
```
when the url = "http://zh.html.net/tutorials/css/lesson3.php", it fails, and alarm: 

** (FunctionClauseError) no function clause matching in Floki.HTMLTree.build/1
    (floki) lib/floki/html_tree.ex:14: Floki.HTMLTree.build(nil)
    (floki) lib/floki/finder.ex:48: Floki.Finder.find_selectors/2
    (floki) lib/floki/filter_out.ex:17: Floki.FilterOut.filter_out/2
    (floki) lib/floki.ex:210: Floki.text/2
    (readability) lib/readability/helper.ex:75: Readability.Helper.text_length/1
    (readability) lib/readability/article_builder.ex:36: Readability.ArticleBuilder.build/2

when the url = "http://html.net/tutorials/css/lesson3.php", it works well.

so it  seems support Chiness not well.

**Comment by Valian** [comment]
It's a very old issue, and for me it works with the newest version just fine (v0.12.0). Closing as no longer relevant, please open a new issue if something doesn't work as expected.
