### ISSUE TITLE
Support current version of Elixir and Floki

### ISSUE THREAD

**Issue by keepcosmos** [keepcosmos/readability#31]
Support elixir 1.5 and floki 0.18

**Comment by adlan** [comment]
let me take this

**Comment by adlan** [comment]
I created a PR for this. However, I just realized that the CI build will fail for Elixir 1.2.6 because Floki requires at least 1.3.0. Would you like to bump the minimum Elixir version required?

**Comment by keepcosmos** [comment]
Sure, Elixir version should be updated! :) Thanks

**Comment by adlan** [comment]
Great! I'll add to the PR to update the travis config file and update the README file
