### ISSUE TITLE
Dependency versions too old

### ISSUE THREAD

**Issue by alexandremcosta** [keepcosmos/readability#44]
```
{:httpoison, "~> 0.13.0"},
```

This forces everyone with an updated codebase to use `override: true`
```
{:httpoison, "~> 1.5", override: true}
```

I know it's hard to keep the lib updated, but at least make the dependencies more open for updates

**Comment by zpeters** [comment]
#45 A few other were out of date.  Updated everything and made sure tests passed

**Comment by everettvody** [comment]
Is this being updated?
